package types

const (
	RequestBalanceTransferAPI    = "/api/v0/request/transfer/balance"
	ConfirmBalanceTransferAPI    = "/api/v0/confirm/transfer/balance"
	RejectBalanceTransferAPI     = "/api/v0/reject/transfer/balance"
	RequestBalanceWithdrawAPI    = "/api/v0/request/withdraw/balance"
	ConfirmBalanceWithdrawAPI    = "/api/v0/confirm/withdraw/balance"
	RejectBalanceWithdrawAPI     = "/api/v0/reject/withdraw/balance"
	ListBalanceRequestAPI        = "/api/v0/list/balance/request"
	ListAccountsAPI              = "/api/v0/list/accounts"
	AccountInfoAPI               = "/api/v0/account/info"
	MinerInfoAPI								 = "/api/v0/miner/info"
	ListMinersAPI                = "/api/v0/list/miners"
	AddAccountAPI                = "/api/v0/add/account"
	AddMinerAPI                  = "/api/v0/add/miner"
	AddTransferHistoryAPI        = "/api/v0/add/transfer"
	AddWithdrawHistoryAPI        = "/api/v0/add/withdraw"
	UserLoginAPI                 = "/api/v0/user/login"
	AddUserAPI                   = "/api/v0/add/user"
	UserInfoAPI                  = "/api/v0/user/info"
	ListReviewersAPI             = "/api/v0/list/reviewers"
	ListRolesAPI                 = "/api/v0/list/roles"
	ListWalletTypesAPI           = "/api/v0/list/wallet/types"
	ListMinerWalletTypesAPI      = "/api/v0/list/miner/wallet/types"
	AddCustomerAPI               = "/api/v0/add/customer"
	ListCustomersAPI             = "/api/v0/list/customers"
	SetBalanceTransferTargetsAPI = "/api/v0/set/balance/transfer/targets"
	GetBalanceTransferTargetsAPI = "/api/v0/get/balance/transfer/targets"
	TransferBalanceAPI           = "/api/v0/transfer/balance"
	ListReviewHistoryAPI				 = "/api/v0/list/review/history"
	WithdrawBalanceAPI					 = "/api/v0/withdraw/balance"
	HandlingFeeAPI							 = "/api/v0/handling/fee"
	QueryHandlingStatusAPI 			 = "/api/v0/query/handling/status"
	ListUsersAPI								 = "/api/v0/list/users"
	DeleteUserAPI								 = "/api/v0/delete/user"
	ChangeUserAPI								 = "/api/v0/change/user"
)
